config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only:[:index, :show, :edit, :update, :destroy]
  resources :books, only:[:index, :new, :show, :edit, :create, :update, :destroy] do
    resources :rentals, only:[:create, :destroy]
    resources :bookmarks, only:[:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :categories, only:[:index, :new, :show, :create, :edit, :update, :destroy]
  resources :rentals, only:[:index]
  post 'homes/guest_sign_in', to: 'homes#guest_sign_in'
  post 'homes/admin_sign_in', to: 'homes#admin_sign_in'
  get '/booksearch', to: 'books#new'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rentals, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20}
  validates :email, presence: true, uniqueness: true

  attachment :image
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.includes(:rentals).order(name: :desc)
  end

  def show
    @user = User.find(params[:id])
    @bookmarks = @user.bookmarks
    @rentals =  @user.rentals
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(users_params)
    flash[:success] = "プロフィールを更新しました。"
    redirect_to user_path(@user)
  end

  private 

  def users_params
    params.require(:user).permit(:name, :email, :image, :password, :password_confirmation )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
<%= render "layouts/flash" %>
  <div class="col-md-12 pt-3">
    <h2 class="text-center mt-5 font-weight-bold mb-4 border-bottom">マイページ編集</h2>
    <div class="container">
    <div class="col-md-8 offset-md-2 pt-5">
    <%= form_with model: @user, local: true do |f| %>
      <% flash.each do |key, value| %>
        <div class="alert alert-danger alert-dismissible">
          <button class="close" data-dismiss="alert">&times;</button>
          <span class="alert alert-<%= key %>",style="border: none;"><%= value %></span>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :プロフィール写真 %><br />
        <%= attachment_image_tag @user, :image, class:"rounded-circle mb-2", size:"100x100", fallback:"no_image_icon.jpg"%>
        <%= f.attachment_field :image %>
      </div>

      <div class="form-group">
        <%= f.label :名前 %><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "email" , class:"form-control"%>
      </div>

      <div class="form-group">
        <%= f.label :メールアドレス %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" , class:"form-control"%>
      </div>

      <div class="actions">
        <%= f.submit "更新", style:"background-color:#7b9ad0; color: white;",class:"btn w-100" %>
      </div>
    <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
  <div class="col-md-12 pt-3">
   <%= render "layouts/flash" %>
    <h2 class="text-center mt-5 font-weight-bold">ユーザー一覧</h2>
  </div>
<div class="container mt-5">
<ul class="nav nav-tabs text-center bg-light mb-3" id="myTab" role="tablist">
  <li class="nav-item w-50">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">全ユーザー</a>
  </li>
  <li class="nav-item w-50">
    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">利用中のユーザー</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <div class="row d-flex">
  <% @users.each do |u| %>
    <div class="col-lg-2 col-md-4 col-sm-6 col-6 mt-2 mb-2 text-center">
    <div class="border rounded pt-3 pb-3">
      <%= link_to user_path(u) do %>
        <%= attachment_image_tag u, :image, class:"rounded-circle mb-2", size:"100x100", fallback:"no_image_icon.jpg"%> <br>
        <%= u.name %> <br>
        <%= u.email %> <br>
        貸出数:<%= u.rentals.size %>
      <% end %>
    </div>
    </div>
  <% end %>
  </div>
  </div>
  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
  <div class="row d-flex">
  <% @users.each do |u| %>
   <% if u.rentals.exists? %>
    <div class="col-lg-2 col-md-4 col-sm-6 col-6 mt-2 mb-2 text-center">
    <div class="border rounded">
      <%= link_to user_path(u) do %>
        <%= attachment_image_tag u, :image, class:"rounded-circle", size:"100x100", fallback:"no_image_icon.jpg"%> <br>
        <%= u.name %> <br>
        <%= u.email %> <br>
        貸出数:<%= u.rentals.size %>
      <% end %>
    </div>
    </div>
  <% end %>
  <% end %>
  </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<%= render "layouts/flash" %>
  <div class="col-md-12 pt-3">
    <h2 class="text-center mt-5 font-weight-bold mb-4 border-bottom">マイページ</h2>
    <div class="border rounded mt-2 mb-2 pb-4 text-center">
    <div class="d-sm-flex">
      <div class="col-md-4 col-sm-3 col-12 pt-3 pb-3 ">
      <%= attachment_image_tag @user, :image, class:"rounded-circle mb-2", size:"100x100", fallback:"no_image_icon.jpg"%> <br>
      </div>
      <div class="col-md-8 col-sm-9 col-12">
        <table class="table table-borderless">
          <tr>
            <th>名前</th>
            <th>メール</th>
            <th>レンタル数</th>
          </tr>
          <tr>
            <td><%= @user.name %></td>
            <td><%= @user.email %></td>
            <td><%= @user.rentals.size %></td>
          </tr>
          <tr>
            <% if @user.id == current_user.id %>
            <th colspan="3"><%= link_to "編集", edit_user_path, class:"btn w-100", style:"background-color:#7b9ad0; color: white;", local: true %></th>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
    <div class="d-lg-flex">
    <div class="col-lg-6 col-md-12 col-sm-12 border-right">
    <h3 class="border-bottom font-weight-bold">ブックマーク</h3>
    <table class="table table-borderless">
    <%  if @bookmarks.empty? %>
      <h5 class="font-weight-bold mt-5"> ブックマークはありません。</h5>
    <% else %>
    <% @bookmarks.each do |b| %>
    <thead>
      <th>書籍画像</th>
      <th>タイトル</th>
      <th></th>
    </thead>
    <tbody>
      <tr>
        <td>
          <% if b.book.image_url.nil? %>
            <img src="/assets/no_image.png" width="100" vspace="2">
          <% else %>
            <img src="<%= b.book.image_url %>" width="100" vspace="2">
          <% end %>
        </td>
        <td class="align-middle">
          <%= link_to book_path(b.book)  do %>
            <%= b.book.title %>
          <% end %>
        </td>
        <td class="align-middle">
        <% if b.user_id == current_user.id %>
          <%= link_to book_bookmark_path(b.book_id, current_user), method: :delete, data:{ confirm: "ブックマークを解除してよろしいでしょうか？"}, local: true do %>
          <i class="fas fa-bookmark btn btn-danger"></i>
          <% end %>
        <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
     <% end %>
    </table>
   </div>
   <div class="col-lg-6 col-md-12 col-sm-12 border-right">
    <h3 class="border-bottom font-weight-bold">レンタル書籍</h3>
    <table class="table table-borderless">
    <%  if @rentals.empty? %>
      <h5 class="font-weight-bold mt-5"> 借りている本はありません。</h5>
    <% else %>
    <% @rentals.each do |r| %>
    <thead>
      <th>書籍画像</th>
      <th>タイトル</th>
      <th></th>
    </thead>
    <tbody>
      <tr>
        <td>
          <% if r.book.image_url.nil? %>
            <img src="/assets/no_image.png" width="100" vspace="2">
          <% else %>
            <img src="<%= r.book.image_url %>" width="100" vspace="2">
          <% end %>
        </td>
        <td class="align-middle">
           <%= link_to book_path(r.book)  do %>
            <%= r.book.title %>
          <% end %>
        </td>
        <td class="align-middle">
        <% if r.user_id == current_user.id %>
          <%= link_to book_rental_path(r.book_id, current_user), method: :delete, data:{ confirm: "返却してよろしいでしょうか？"}, local: true do %>
          <i class="fas fa-undo btn btn-danger"></i>
          <% end %>
        <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
    <% end %>
    </table>
   </div>
  </div>
  </div>
</div>