config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only:[:index, :show, :edit, :update, :destroy]
  resources :books, only:[:index, :new, :show, :edit, :create, :update, :destroy] do
    resources :rentals, only:[:create, :destroy]
    resources :bookmarks, only:[:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :categories, only:[:index, :new, :show, :create, :edit, :update, :destroy]
  resources :rentals, only:[:index]
  post 'homes/guest_sign_in', to: 'homes#guest_sign_in'
  post 'homes/admin_sign_in', to: 'homes#admin_sign_in'
  get '/booksearch', to: 'books#new'
end

app/models/book.rb
class Book < ApplicationRecord
  has_many   :rentals, dependent: :destroy
  has_many   :bookmarks, dependent: :destroy
  belongs_to :category

  validates :title, presence: true, length: {maximum: 100}
  validates :author, length: {maximum: 40 }
  validates :publisher, length: {maximum: 40 }
  validates :volume, length: {maximum: 3 }
  validates :stock_num, presence: true, length: {maximum: 1 }

  def rental_status
    if stock_num == 0
       "貸出中"
    else
      "貸出可能"
      "#{stock_num}冊貸出可能"
    end
  end

  def rentaled_by?(user)
    rentals.where(user_id: user.id).exists?
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search != ""
      Book.where(['title LIKE(?) OR isbn LIKE(?) OR author LIKE(?)  OR publisher LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
      else
        Book.order('created_at DESC')
      end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.order(title: :desc)
  end

  def new
    unless current_user.is_admin
      redirect_to books_path
    end
    @book = Book.new

    #書籍検索APIの処理
    if params[:keyword].present?
      require 'net/http'
      url = 'https://www.googleapis.com/books/v1/volumes?q='
      request = url + params[:keyword]
      enc_str = URI.encode(request)
      uri = URI.parse(enc_str)
      json = Net::HTTP.get(uri)
      @bookjson = JSON.parse(json)

      count = 10
      @books = Array.new(count).map{Array.new(7)}
      count.times do |x|
        @books[x][0] = @bookjson.dig("items", x, "volumeInfo", "title")
        @books[x][1] = @bookjson.dig("items", x, "volumeInfo", "imageLinks", "thumbnail")
        @books[x][2] = @bookjson.dig("items", x, "volumeInfo", "authors")
        @books[x][2] = @books[x][2].join(',') if @books[x][2] #複数著者をカンマで区切る
        @books[x][3] = @bookjson.dig("items", x, "volumeInfo", "publisher")
        @books[x][4] = @bookjson.dig("items", x, "volumeInfo", "publishedDate")
        @books[x][5] = @bookjson.dig("items", x, "volumeInfo", "industryIdentifiers", 1, "identifier")
        @books[x][6] = @bookjson.dig("items", x, "volumeInfo", "pageCount")
      end
    end

      @title = params[:title] if params[:title].present?
      @code = params[:code] if params[:code].present?
      @author = params[:author] if params[:author].present?
      @publisher = params[:publisher] if params[:publisher].present?
      @published_date = params[:publishedDate] if params[:publishedDate].present?
      @img = params[:img] if params[:img].present?
      @page = params[:pageCount] if params[:pageCount].present?
  end

  def show
    @book = Book.find(params[:id])
    @rental = Rental.find_by(user_id: current_user.id)
  end

  def create
    @book = Book.new(books_params)
    if @book.save
      flash[:success] = "書籍の登録が完了しました。"
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def edit
    unless current_user.is_admin
      redirect_to books_path
    end
   @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(books_params)
      flash[:success] = "書籍情報を更新しました。"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:success] = "書籍情報を削除しました。"
      redirect_to books_path
    else
      render :show
    end
  end

  def search
    @books = Book.search(params[:keyword])
  end

  private

  def books_params
    params.require(:book).permit(:title, :isbn, :image_url, :author, :publisher, :published_date, :category_id, :volume, :stock_num)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_search.html.erb
<%= form_with(url: search_books_path, local: true, method: :get, class:"w-100") do |f| %>
  <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "form-control" %>
  <%= f.submit "検索", class: "btn btn-primary w-100", style:"background-color:#7b9ad0; color: white;" %>
<% end %>

app/views/books/edit.html.erb
<div class="d-flex container">
  <div class="col-md-12 pt-3 mb-5">
    <h2 class="text-center mt-5 font-weight-bold border-bottom">書籍情報編集</h2>
    </div>
  </div>
<div class="container">
 <%= form_with model: @book, local: true do |f| %>
  <div class="mb-1" style="max-width: auto;">
    <div class="col-md-12 col-sm-12">
      <div class="card-body">
      <table class="table">
        <h4 class="card-title font-weight-bold mb-4">
          <%= f.text_field :title, placeholder:"書籍のタイトルを入力してください。", class:"form-control" %>
        </h4>
        <tbody>
        <tr>
          <th class="card-text text-center text-center">書籍画像</th>
          <td><%= f.text_field :image_url, class:"form-control" %></td>
        </tr>
        <tr>
          <th class="card-text text-center">ISBN番号</th>
          <td><%= f.text_field :isbn, class:"form-control" %></td>
        </tr>
        <tr>
          <th class="card-text text-center">著者名</th>
          <td><%= f.text_field :author, class:"form-control" %></td>
        </tr>
        <tr>
          <th class="card-text text-center">出版者名</th>
          <td><%= f.text_field :publisher, class:"form-control" %></td>
        </tr>
        <tr>
          <th class="card-text text-center">出版年月</th>
          <td><%= f.text_field :published_date, class:"form-control" %></td>
        </tr>
        <tr>
          <th class="card-text text-center">カテゴリー</th>
          <td><%= f.collection_select :category_id, Category.all, :id, :name, include_blanck: "選択してください", class:"w-50 form-control" %></td>
        </tr>
        <tr>
          <th class="card-text text-center">容量</th>
          <td><%= f.text_field :volume, class:"w-25", placeholder:"ページ数を入力してください。", class:"form-control" %> ページ</td>
        </tr>
        <tr>
          <th class="card-text text-center">冊数</th>
          <td><%= f.text_field :stock_num, class:"w-25", placeholder:"何冊ありますか？", class:"form-control" %> 冊</td>
        </tr>
        </tbody>
      </table>
        <%= f.submit "更新", class:"btn btn-primary w-100"%>
    </div>
  <% end %>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
  <%= render "layouts/flash" %>
  <div class="d-flex">
  <div class="col-md-12 pt-3">
    <h2 class="text-center mt-5 font-weight-bold border-bottom">書籍一覧</h2>
    <div class="pt-5">
      <div class="mb-5">
        <%= render "books/search"%>
      </div>
     <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item w-50 text-center">
        <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">貸出可能書籍</a>
      </li>
      <li class="nav-item w-50 text-center">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">貸出中</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <div class="d-flex flex-wrap">
          <% @books.each do |b| %>
            <% if b.stock_num > 0 %>
              <div class="book-lists col-xl-2 col-md-2 col-sm-3 col-4 mt-3 text-center">
                <%= link_to book_path(b) do %>
                 <% if b.image_url.nil? || b.image_url.empty?%>
                    <img src="/assets/no_image.png" width="100" vspace="2">
                  <% else %>
                   <img src="<%= b.image_url %>" width="100" vspace="2">
                  <% end %>
                  <div class="text-center small mr-4 ml-4">
                    <%= b.title.truncate(20)%>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
        <div class="d-flex flex-wrap">
          <% @books.each do |b| %>
            <% if b.stock_num == 0 %>
              <div class="book-lists col-xl-2 col-md-2 col-sm-3 col-4 mt-3 text-center">
                <%= link_to book_path(b) do %>
                  <% if b.image_url.nil? || b.image_url.empty?%>
                    <img src="/assets/no_image.png" width="100" vspace="2">
                  <% else %>
                   <img src="<%= b.image_url %>" width="100" vspace="2">
                   <% end %>
                  <div class="text-center small mr-4 ml-4">
                    <div class="linkedit">
                      <%= b.title.truncate(20) %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
  </div>
</div>
</div>

app/views/books/new.html.erb
<div class="container">
<div class="col-md-12 pt-3">
<h2 class="text-center border-bottom font-weight-bold mt-5">書籍登録</h2>
<div>
 <div class="col-md-12">
  <%= form_tag('/booksearch', method: :get) do %>
    <div class="input-group">
      <%= search_field_tag "keyword", params[:keyword], class: "form-control", placeholder: "キーワード検索" %>
        <span class="input-group-btn">
          <%= submit_tag "検索", class: "btn btn-primary" %>
        </span>
    </div>
  <% end %>
<% if @books.present? %>
<h2 class="text-center border-bottom mt-4 font-weight-bold">検索結果</h2>
  <div class="d-flex flex-wrap">
    <% @books.each do |book| %>
      <div class="book-lists col-xl-2 col-md-3 col-sm-3 col-4 mt-3 text-center small">
      <div class=" mr-1 ml-1 border rounded">
        <div class="col-12">
        <img src="<%= book[1] %>" width="100%" vspace="2">
        </div>
        <%= link_to book[0], controller: "books", action: "new", title: book[0], code: book[5], author: book[2], publisher: book[3], publishedDate: book[4], img: book[1], pageCount: book[6] %> <br>
        <%= book[2] %> <br>
        <%= book[3] %> <br>
        出版年月:<%= book[4] %> <br>
        ISBN番号: <%= book[5] %> <br>
        ページ数: <%= book[6] %> <br>
      </div>
      </div>
    <% end %>
  </div>
<% end %>
</div>
<div class="col-md-12 mt-5">
<%= form_with model: @book, method: :post, local: true do |f| %>
  <%= render "layouts/error_messages", resource: @book %>
  <table>
   <h3 class="text-danger font-weight-bold text-center">注意: カテゴリーを必ず選択してください！</h3>
  <div class="form-group">
    <%= f.label :タイトル %>
    <%= f.text_field :title, class:"form-control", placeholder:"書籍のタイトルを入力してください。", value: "#{@title}"%>
  </div>
  <div class="form-group">
    <%= f.label :ISBN番号 %>
    <%= f.text_field :isbn, class:"form-control", placeholder:"13桁で入力。", value: "#{@code}"%>
  </div>
  <div class="form-group">
    <%= f.label :書籍画像 %> <br>
    <%= f.text_field :image_url, class: 'form-control', value: "#{@img}" %>
  </div>
  <div class="form-row mb-3">
    <div class="col-md-6">
    <%= f.label :著者 %>
    <%= f.text_field :author, class:"form-control", value: "#{@author}" %>
    </div>
    <div class="col-md-6">
    <%= f.label :出版者 %>
    <%= f.text_field :publisher, class:"form-control", value: "#{@publisher}" %>
    </div>
  </div>
  <div class="form-row mb-3">
    <div class="col-md-2">
      <%= f.label :出版年月 %> <br>
      <%= f.text_field :published_date, class:"form-control", value: "#{@published_date}" %>
    </div>
    <div class="col-md-4">
      <%= f.label :カテゴリー %> <br>
      <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: "選択してください", class:"form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :容量・ページ数 %>
      <%= f.text_field :volume, class:"form-control", size: "30", placeholder:"ページ数を入力", value: "#{@page}"%>
    </div>
    <div class="col-md-3">
      <%= f.label :部数 %>
      <%= f.text_field :stock_num, class:"form-control", placeholder:"何冊ありますか？"%>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "書籍登録", class:"btn btn-primary w-100"%>
  </div>
  </table>
<% end %>
</div>
</div>
</div>

app/views/books/search.html.erb
<div class="container pt-3">
  <h2 class="text-center mt-5 mb-5 font-weight-bold border-bottom">検索結果一覧</h2>
  <div class="mb-5">
    <%= render "books/search"%>
  </div>
  <% if @books== [] %>
    <h2 class = "text-center font-weight-bold mt-5 pt-5">
      検索結果はありません <br>
      検索キーワードを変えて、再検索してみてください。
    </h2>
  <% else %>
    <div class="d-flex flex-wrap">
      <% @books.each do |b| %>
        <div class="book-lists col-xl-2 col-md-2 col-sm-3 col-4 mt-3 text-center">
          <%= link_to book_path(b) do %>
            <% if b.image_url.nil? || b.image_url.empty? %>
              <img src="/assets/no_image.png" width="100" vspace="2">
            <% else %>
              <img src="<%= b.image_url %>" width="100" vspace="2">
            <% end %>
            <div class="text-center small mr-4 ml-4">
              <% if b.stock_num == 0 %>
                <div class="linkedit">
                  <%= b.title.truncate(20)%>
                </div>
              <% else%>
                <%= b.title.truncate(20)%>
              <% end %>
            </div>
            <% end %>
        </div>
      <% end %>
     </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="container">
  <%= render "layouts/flash" %>
  <div class="d-flex">
  <div class="col-md-12 pt-3 mb-5">
    <h2 class="text-center mt-5 font-weight-bold border-bottom">書籍詳細</h2>
    </div>
  </div>
<div class="container">
  <div class="mb-1" style="max-width: auto;">
  <div class="row no-gutters">
    <div class="col-md-6 col-sm-12 text-center">
      <% if @book.image_url.nil? || @book.image_url.empty? %>
        <img src="/assets/no_image.png" width="300" vspace="2">
      <% else %>
        <img src="<%= @book.image_url %>" width="300" vspace="2">
      <% end %>
    </div>
    <div class="col-md-6 col-sm-12">
      <div class="card-body">
      <table class="table">
        <h4 class="card-title font-weight-bold mb-4"><%= @book.title %></h4>
        <tbody>
        <tr>
          <th class="card-text mt-5">ISBN番号:</th>
          <td><%= @book.isbn %></td>
        </tr>
        <tr>
          <th class="card-text">著者名:</th>
          <td><%= @book.author %></td>
        </tr>
        <tr>
          <th class="card-text">出版者名:</th>
          <td><%= @book.publisher %></td>
        </tr>
        <tr>
          <th class="card-text">出版年月:</th>
          <td><%= @book.published_date %></td>
        </tr>
        <tr>
          <th class="card-text">カテゴリー:</th>
          <td>
            <%= link_to category_path(@book.category) do %>
            <%= @book.category.name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="card-text">容量:</th>
          <td><%= @book.volume %> ページ</td>
        </tr>
        <tr>
          <th class="card-text">貸出状況:</th>
          <td><%= @book.rental_status %></td>
        </tr>
        </tbody>
      </table>
        <% if user_signed_in? && current_user.is_admin? %>
          <%= link_to "編集する", edit_book_path(@book), class:"btn btn-success w-100 mb-1"%>
          <%= link_to "削除する", book_path(@book), method: :delete, class:"btn btn-danger w-100 mb-1", data: {confirm: "削除してよろしいでしょうか？"}%>
        <% end %>
          <% if @book.bookmarked_by?(current_user) %>
            <%= link_to book_bookmark_path(book_id: @book.id), method: :delete, class:"btn btn-secondary w-100 mb-1", data:{ confirm: "ブックマークを解除してよろしいでしょうか？"}, local: true do %>
            ブックマークをやめる<i class="fas fa-bookmark"></i>
            <% end %>
          <% else %>
            <%= link_to book_bookmarks_path(book_id: @book.id), method: :post, class:"btn btn-info w-100 mb-1", local: true do %>
              ブックマークする<i class="far fa-bookmark"></i>
            <% end %>
          <% end %>
          <% if @book.stock_num > 0 %>
            <% if @book.rentaled_by?(current_user) %>
              <%= link_to book_rental_path(book_id: @book.id), method: :delete, class:"btn btn-danger w-100" ,local: true do %>
                返却する
              <% end %>
            <% else %>
              <%= link_to book_rentals_path(book_id: @book.id), method: :post, class: "btn btn-primary w-100", local: true do %>
                借りる
              <% end %>
            <% end %>
          <% else %>
            <% if @book.rentaled_by?(current_user) %>
              <%= link_to book_rental_path(book_id: @book.id), method: :delete, class:"btn btn-danger w-100", data:{ confirm: "#{@book.title }返却してよろしいでしょうか？"}, local: true do %>
                返却する
              <% end %>
            <% else %>
              <%= link_to rentals_path, class: "btn btn-warning w-100" do %>
                他の誰かが借りています。
              <% end %>
            <% end %>
          <% end %>
        <th class="card-text mt-5"><small class="text-muted">更新日：<%= @book.updated_at.strftime('%Y年%m月%d日')%></small></th>
       <div>
    </div>
  </div>
</div>
</div>
</div>
</div>