config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only:[:index, :show, :edit, :update, :destroy]
  resources :books, only:[:index, :new, :show, :edit, :create, :update, :destroy] do
    resources :rentals, only:[:create, :destroy]
    resources :bookmarks, only:[:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :categories, only:[:index, :new, :show, :create, :edit, :update, :destroy]
  resources :rentals, only:[:index]
  post 'homes/guest_sign_in', to: 'homes#guest_sign_in'
  post 'homes/admin_sign_in', to: 'homes#admin_sign_in'
  get '/booksearch', to: 'books#new'
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :books
  validates :name, presence: true, uniqueness:true, length: {maximum: 30}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.all.includes(:books)
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @books = @category.books
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      flash[:success] = "ジャンルを追加しました"
      redirect_to categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def edit
    @category = Category.find(params[:id])
    unless current_user.is_admin
      redirect_to categories_path
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(categories_params)
      flash[:success] = "カテゴリーの更新をしました。"
      redirect_to categories_path
    else
      flash[:danger] = "カテゴリーの更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:success] = "ジャンルを削除しました。"
      redirect_to categories_path
    else
      @categories = Category.all
      flash[:danger] = "カテゴリーを削除できませんでした。"
      render :index
    end
  end

  private

  def categories_params
    params.require(:category).permit(:name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="container">
  <div class="col-md-8 offset-md-2 pt-3">
  <h2 class="text-center mt-5 font-weight-bold">カテゴリー編集</h2>
  <%= form_with model: @category, local: true do |f| %>
    <% flash.each do |key, value| %>
      <div class="alert alert-danger alert-dismissible">
        <button class="close" data-dismiss="alert">&times;</button>
        <span class="alert alert-<%= key %>",style="border: none;"><%= value %></span>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :カテゴリー名 %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "email" , class:"form-control"%>
    </div>
    <div class="actions">
      <%= f.submit "更新",class:"btn btn-success w-100" %>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="container">
<%= render "layouts/flash"%>
  <div class="col-md-12 pt-3">
  <% if current_user.is_admin? %>
    <h2 class="text-center mt-5 font-weight-bold">カテゴリー登録</h2>
    <%= form_with model: @category, local: true do |f| %>
    <%= render "layouts/error_messages", resource: @category%>
      <div class="form-group mt-4">
        <%= f.text_field :name, class:"w-100 form-control", placeholder: "カテゴリー名を追加してください。"%>
        <%=f.submit "登録", class:"btn btn-success w-100"%>
      </div>
    <% end %>
  <% end %>
  <h2 class="text-center mt-5 font-weight-bold mb-4">カテゴリー一覧</h2>
  <div>
  <table class="table">
    <thead class="thead-dark">
      <tr class="text-center">
        <th>No.</th>
        <th>カテゴリー名</th>
        <th>書籍数</th>
        <th></th>
      </tr>
    </thead>
    <% @categories.each do |c| %>
      <tbody>
        <tr>
          <td class="text-center"><%= c.id %></td>
          <td class="text-center">
            <%= link_to category_path(c) do %>
            <%= c.name %>
            <% end %>
          </td>
          <td class="text-center">
            <%= c.books.size %> 冊
          </td>
          <td class="text-center">
            <% if current_user.is_admin? %>
              <%= link_to "編集", edit_category_path(c), class:"btn btn-success"%>
              <%= link_to "削除", category_path(c), method: :delete,  class:"btn btn-danger", data: {confirm: "削除してよろしいでしょうか？"}%>
            <% end %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/categories/show.html.erb
<%= render "layouts/flash" %>
<div class="d-flex container">
  <div class="col-md-12 pt-3">
    <h2 class="text-center mt-5 font-weight-bold border-bottom"> <%= @category.name %> ジャンルの書籍一覧 (全 <%= @books.size %> 冊)</h2>
<div class="d-flex">
  <% @books.each do |b| %>
    <div class="book-lists col-xl-2 col-md-2 col-sm-3 col-4 mt-3 text-center">
      <%= link_to book_path(b) do %>
        <% if b.image_url.nil? %>
          <img src="/assets/no_image.png" width="100" vspace="2">
         <% else %>
          <img src="<%= b.image_url %>" width="100" vspace="2">
        <% end %>
        <div class="text-center small mr-4 ml-4">
        <% if b.stock_num == 0 %>
          <div class="linkedit">
            <%= b.title.truncate(20)%>
          </div>
        <% else %>
          <%= b.title.truncate(20)%>
        <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>