config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only:[:index, :show, :edit, :update, :destroy]
  resources :books, only:[:index, :new, :show, :edit, :create, :update, :destroy] do
    resources :rentals, only:[:create, :destroy]
    resources :bookmarks, only:[:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :categories, only:[:index, :new, :show, :create, :edit, :update, :destroy]
  resources :rentals, only:[:index]
  post 'homes/guest_sign_in', to: 'homes#guest_sign_in'
  post 'homes/admin_sign_in', to: 'homes#admin_sign_in'
  get '/booksearch', to: 'books#new'
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
　<div class="alert alert-danger alert-dismissible">
    <button class="close" data-dismiss="alert">&times;</button>
    <h4>入力した内容にエラーが<%= resource.errors.count %>件あります</h4>
    <ul class="list-group">
      <% resource.errors.full_messages.each do |message| %>
        <li class="list-group"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-success alert-dismissible">
    <button class="close" data-dismiss="alert">&times;</button>
      <span class="alert alert-<%= key %>" style="border: none;"><%= value %></span>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>借りルンです</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body class="d-flex flex-column">
    <header class="shadow-md" style="background-color:#7b9ad0;">
      <nav class="navbar navbar-expand-sm navbar-light">
          <%if user_signed_in? %>
          <a class="navbar-brand p-4 text-white" href="/books">借りルンです</a>
          <% else %>
          <a class="navbar-brand p-4 text-white" href="/">借りルンです</a>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto text-center">
            <% if user_signed_in? %>
              <li class="nav-item ">
                <%= link_to " 書籍一覧", books_path, class: 'fas fa-book-open nav-link text-white' %>
              </li>
              <% if current_user.is_admin? %>
                <li class="nav-item">
                  <%= link_to " 書籍登録", new_book_path, class: 'fas fa-edit nav-link text-white' %>
                </li>
              <% end %>
              <li class="nav-item">
                <%= link_to " 貸出状況", rentals_path, class: 'fas fa-clipboard-list nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to " ユーザー一覧", users_path, class: 'fas fa-users nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to " カテゴリー", categories_path, class: 'fas fa-folder-open nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to " #{current_user.name}", user_path(current_user), class: 'fas fa-user nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to " ログアウト", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-white' %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to " 新規登録", new_user_registration_path, class: 'fas fa-user nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to " ログイン", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to " ゲストログイン", homes_guest_sign_in_path, method: :post, class: 'fas fa-sign-in-alt nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to " 管理者ログイン", homes_admin_sign_in_path, method: :post, class: 'fas fa-user-shield nav-link text-white' %>
              </li>
            <% end %>
            </ul>
          </div>
      </nav>
    </header>
      <%= yield %>
  </body>
</html>